version: '3.8'

services:
  client:
    build:
      context: ./client/kanban
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - kanbanNetwork
    
  server:
    build:
      context: ./server/Kanban/Kanban
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/kanban
      - SPRING_DATASOURCE_USERNAME=postgresql
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db
    networks:
      - kanbanNetwork
    
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=kanban
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=root
    volumes:
      - kanbanData:/var/lib/postgresql/data
    networks:
      - kanbanNetwork

volumes:
  kanbanData:

networks:
  kanbanNetwork:
    driver: bridge